CREATE OR REPLACE VIEW `produccion.Vw_TABLA_Anulaciones` AS
SELECT FECHA_INGRESO, TIPO_SEGURO, ESTADO_GENERAL, 
        ESTADO, COMENTARIO, OBSERVACIONES, DIVISA_ORIGINAL_PRIMA, 
        IMPORTE_DIVISA_ORIG_PRIMAS_DEVUELTAS, OBS_RIMAC,
        OBSERV_LEVANTADAS_BANCO, 
FROM `produccion.TABLA_Anulaciones`