
SELECT EXTRACT(MONTH FROM FECHA_DE_AFILIACION) AS MES, MONEDA, FORMAT("%'d", COUNT(*)) AS CANTIDAD, FORMAT("%'.2f", SUM(PRIMA_BRUTA)) AS TOTAL_PRIMA
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND TIPO_DE_REGISTRO = '01' AND TIPO_DE_MOVIMIENTO = '1'
GROUP BY MES, MONEDA
ORDER BY MES ASC;

SELECT MONEDA, FORMAT("%'.2f", SUM(PRIMA_BRUTA)) AS TOTAL_PRIMA
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND TIPO_DE_REGISTRO = '01' AND TIPO_DE_MOVIMIENTO = '4'
GROUP BY MONEDA;

SELECT CERTIFICADO, FECHA_DE_AFILIACION, PLAN_DE_SEGURO, MONEDA, PRIMA
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND PLAN_DE_SEGURO= '01' AND FECHA_DE_AFILIACION BETWEEN '2023-01-01' AND '2023-02-28';


SELECT *
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND FECHA_DE_AFILIACION BETWEEN '2023-12-01' AND '2023-12-31';


-------------------------- vista para el dasboard Karina --------------------------------------
CREATE OR REPLACE VIEW `produccion.Vw_Tramas_Diarias_BBVA` AS
SELECT FECHA_DE_AFILIACION, TIPO_DE_SEGURO, 
        TIPO_DE_MOVIMIENTO, TIPO_DE_REGISTRO, PLAN_DE_SEGURO, PERIODO_DE_PAGO,
        MONEDA, COUNT(*) AS CONTIDAD, SUM(PRIMA_BRUTA) AS PRIMA
FROM (
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2020`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2021`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2022`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2023`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2024`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2025`
)
GROUP BY FECHA_DE_AFILIACION, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO, TIPO_DE_REGISTRO, PLAN_DE_SEGURO, PERIODO_DE_PAGO, MONEDA;


-------------------------- vista para el dasboard Karen --------------------------------------
CREATE OR REPLACE VIEW `produccion.Vw_Tramas_Diarias_BBVA_FD` AS
SELECT FECHA_DECLARADA, TIPO_DE_SEGURO, 
        TIPO_DE_MOVIMIENTO, TIPO_DE_REGISTRO, 
        MONEDA, COUNT(*) AS CONTIDAD, SUM(PRIMA_BRUTA) AS PRIMA
FROM (
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2020`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2021`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2022`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2023`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2024`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2025`
)
GROUP BY FECHA_DECLARADA, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO, TIPO_DE_REGISTRO, MONEDA;
---------------------------------------------------------------------------------------------
#SELECT CERTIFICADO
#FROM `produccion.tramas_diarias_BBVA_2023`
#WHERE FECHA_DECLARADA = '2023-02-03'

#DELETE
#FROM `produccion.CONTROL_tramas_diarias`
#WHERE ARCHIVO_TXT = 'RED020223_0302.TXT'


WITH tramas_filtro AS (
SELECT *
FROM `produccion.tramas_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND FECHA_DE_AFILIACION BETWEEN '2023-01-01' AND '2023-02-28'
)
SELECT certificado, tipo_de_registro, count(*) AS contador
FROM tramas_filtro
WHERE tipo_de_registro = '01' AND tipo_de_movimiento = '1'
GROUP BY certificado, tipo_de_registro
having contador > 1;

SELECT CERTIFICADO, TIPO_DE_REGISTRO, TIPO_DE_MOVIMIENTO, FECHA_DE_AFILIACION, FECHA_DE_INICIO_DEL_SEGURO, FECHA_TRAMA
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND certificado = '00110465244000795717'
ORDER BY FECHA_DE_AFILIACION ASC;

SELECT CERTIFICADO, TIPO_DE_REGISTRO, TIPO_DE_MOVIMIENTO, FECHA_DE_AFILIACION, FECHA_DE_INICIO_DEL_SEGURO, FECHA_TRAMA
FROM `produccion.tramas_diarias_test`
WHERE TIPO_DE_SEGURO = '829' AND certificado = '00110465264000979923'
ORDER BY FECHA_DE_AFILIACION ASC;

SELECT CERTIFICADO, TIPO_DE_REGISTRO, TIPO_DE_MOVIMIENTO, FECHA_DE_AFILIACION, FECHA_DE_INICIO_DEL_SEGURO
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE TIPO_DE_SEGURO = '803' AND TIPO_DE_REGISTRO = '01' AND TIPO_DE_MOVIMIENTO= '4'
ORDER BY CERTIFICADO, FECHA_DE_AFILIACION ASC;

--------------------------------------------------------
CREATE OR REPLACE TABLE `produccion.tramas_diarias_BBVA2020` AS
SELECT TIPO_DE_SEGURO, CERTIFICADO, NUMERO_INTERNO_DEL_CANAL,TIPO_DE_REGISTRO, 
    MONEDA,TIPO_DE_MOVIMIENTO, FECHA_DE_AFILIACION, FECHA_DE_INICIO_DEL_SEGURO, 
    FECHA_FIN_DEL_SEGURO, PERIODO_DE_PAGO, SUBSTR(TRAMA_ORIGINAL,640,2) AS PLAN_DE_SEGURO,
    PRIMA, TRAMA_ORIGINAL, PRIMA_BRUTA, ERROR_PRIMA, FECHA_TRAMA, FECHA_DECLARADA
FROM `produccion.TRAMAS_diarias_BBVA_2020`;


SELECT PLAN_DE_SEGURO, COUNT(*) AS CONTADOR
FROM `produccion.tramas_diarias_BBVA2023`
GROUP BY PLAN_DE_SEGURO;


CREATE OR REPLACE TABLE `produccion.tramas_diarias_BBVA2023` AS
SELECT *
FROM `produccion.TRAMAS_diarias_BBVA_2023`;


UPDATE `produccion.TRAMAS_diarias_BBVA_2025` 
SET TIPO_DE_SEGURO = '803_TLMK'
WHERE TIPO_DE_SEGURO = '803' AND PLAN_DE_SEGURO <> '01'
    AND FECHA_DECLARADA BETWEEN '2025-09-01'AND '2025-10-31';

SELECT EXTRACT(MONTH FROM FECHA_DE_AFILIACION) AS MES, MONEDA, FORMAT("%'d", COUNT(*)) AS CANTIDAD, FORMAT("%'.2f", SUM(PRIMA_BRUTA)) AS TOTAL_PRIMA
FROM `produccion.TRAMAS_diarias_BBVA_2024`
WHERE TIPO_DE_SEGURO = '803_TLMK' AND TIPO_DE_REGISTRO = '01' AND TIPO_DE_MOVIMIENTO = '4'
GROUP BY MES, MONEDA
ORDER BY MES ASC;

SELECT *
FROM `produccion.TRAMAS_diarias_BBVA_2023`
WHERE CERTIFICADO = '00110253294000495702';

------------------------------------------------------------------------------------------------

WITH conteo_productos AS(
    SELECT FORMAT_DATE('%Y-%m', fecha_declarada) AS MES, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO, 
        COUNT(DISTINCT NOMBRE_DE_ARCHIVO) AS CANT_TRAMAS, count(*) AS CANT_REG
    FROM `produccion.tramas_diarias_2025_Archivo`
    GROUP BY MES, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO
    ORDER BY MES, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO
)
SELECT MES, C.TIPO_DE_SEGURO, P.NOMBRE_PRODUCTO, C.TIPO_DE_MOVIMIENTO, C.CANT_TRAMAS, C.CANT_REG
FROM conteo_productos C
LEFT JOIN `produccion.PRODUCTOS` P ON C.TIPO_DE_SEGURO = P.COD_PRODUCTO
ORDER BY MES, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO;

-----------------

SELECT FORMAT_DATE('%Y-%m', fecha_recepcion) AS MES, Codigo_Subproducto, Descripcion_Producto, nombre_archivo_trama, 
        COUNT(*) AS CANT_TRAMAS
FROM `develop.TABLA_SUSTENTO_BBVA`
WHERE fecha_recepcion BETWEEN '2025-01-01' AND '2025-12-31'
GROUP BY MES, Codigo_Subproducto, Descripcion_Producto, nombre_archivo_trama
ORDER BY MES, Codigo_Subproducto, Descripcion_Producto, nombre_archivo_trama;


----------------------------------------------------------------------------
-----------------------------------------------------------------------------
SELECT
  EXTRACT(YEAR FROM FECHA_DE_AFILIACION) AS ANIO, 
  EXTRACT(MONTH FROM FECHA_DE_AFILIACION) AS MES, 
  TIPO_DE_SEGURO, 
  TIPO_DE_MOVIMIENTO, 
  TIPO_DE_REGISTRO, 
  MONEDA, 
  COUNT(
    CASE 
      WHEN TIPO_DE_SEGURO = '825' AND TIPO_DE_MOVIMIENTO = '1' AND TIPO_DE_REGISTRO = '07' THEN 1
      WHEN TIPO_DE_SEGURO = '825' AND TIPO_DE_MOVIMIENTO = '4' AND TIPO_DE_REGISTRO = '00' THEN 1
      WHEN TIPO_DE_SEGURO = '825' AND TIPO_DE_MOVIMIENTO = '4' AND TIPO_DE_REGISTRO = '01' THEN 1
      WHEN TIPO_DE_SEGURO != '825' THEN 1
    END
  ) AS CANTIDAD,
  SUM(
    CASE 
      WHEN TIPO_DE_SEGURO = '825' AND TIPO_DE_MOVIMIENTO = '1' AND TIPO_DE_REGISTRO = '07' THEN PRIMA_BRUTA
      WHEN TIPO_DE_SEGURO = '825' AND TIPO_DE_MOVIMIENTO = '4' AND TIPO_DE_REGISTRO = '00' THEN PRIMA_BRUTA
      WHEN TIPO_DE_SEGURO = '825' AND TIPO_DE_MOVIMIENTO = '4' AND TIPO_DE_REGISTRO = '01' THEN PRIMA_BRUTA
      WHEN TIPO_DE_SEGURO != '825' THEN PRIMA_BRUTA
    END
  ) AS TOTAL_PRIMA
FROM (
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2021`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2022`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2023`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2024`
    UNION ALL
    SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2025`
    )
WHERE FECHA_DE_AFILIACION BETWEEN '2023-01-01' AND '2025-12-31'
  AND TIPO_DE_MOVIMIENTO IN ('1','4')
GROUP BY ANIO, MES, TIPO_DE_SEGURO, TIPO_DE_MOVIMIENTO, TIPO_DE_REGISTRO, MONEDA
ORDER BY ANIO, MES, TIPO_DE_SEGURO;

------------------------- Consulta para producto de Melisa ---------------------------


WITH filtro_tramas AS (       
  SELECT *
  FROM (
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2020`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2021`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2022`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2023`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2024`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2025`
      )
  WHERE TIPO_DE_SEGURO = '812'AND TIPO_DE_MOVIMIENTO IN ('2','6')
)
SELECT CERTIFICADO, SUBSTR(TRAMA_ORIGINAL, 50, 20) AS APELLIDO_PATERINO, 
        SUBSTR(TRAMA_ORIGINAL, 80, 30) AS APELLIDO_MATERNO,
        SUBSTR(TRAMA_ORIGINAL, 110, 30) AS NOMBRES, FECHA_DE_INICIO_DEL_SEGURO, 
        FECHA_FIN_DEL_SEGURO, PRIMA_BRUTA, TRAMA_ORIGINAL  
FROM (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY CERTIFICADO ORDER BY FECHA_DE_INICIO_DEL_SEGURO DESC) AS ult_v
    FROM filtro_tramas
    )
WHERE ult_v = 1 AND FECHA_DE_INICIO_DEL_SEGURO BETWEEN '2023-01-01' AND '2025-12-31'
ORDER BY CERTIFICADO, FECHA_DE_INICIO_DEL_SEGURO;

----------------------------------------
SELECT C.CERTIFICADO, SUBSTR(TRAMA_ORIGINAL, 50, 20) AS APELLIDO_PATERINO, 
        SUBSTR(TRAMA_ORIGINAL, 80, 30) AS APELLIDO_MATERNO,
        SUBSTR(TRAMA_ORIGINAL, 110, 30) AS NOMBRES, FECHA_DE_INICIO_DEL_SEGURO, 
        FECHA_FIN_DEL_SEGURO, PRIMA_BRUTA, TRAMA_ORIGINAL 
FROM (
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2020`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2021`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2022`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2023`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2024`
        UNION ALL
        SELECT * FROM `produccion.TRAMAS_diarias_BBVA_2025`
      ) td
INNER JOIN `produccion.temp_certificados_pt` c ON c.CERTIFICADO= td.CERTIFICADO
WHERE TIPO_DE_MOVIMIENTO = '4'
ORDER BY c.CERTIFICADO, FECHA_DE_INICIO_DEL_SEGURO;

-------------- Contar tramas por fecha afiliacion ------------------------------------------

SELECT EXTRACT(YEAR FROM FECHA_DE_AFILIACION) AS ANIO, EXTRACT(MONTH FROM FECHA_DE_AFILIACION) AS MES, COUNT (*) AS CANTIDAD
FROM `produccion.TRAMAS_diarias_BBVA_2025`
GROUP BY ANIO, MES
ORDER BY ANIO, MES;

----------------------------------------------
SELECT TIPO_DE_SEGURO, CERTIFICADO, MONEDA, TIPO_DE_MOVIMIENTO, TIPO_DE_REGISTRO, FECHA_DE_AFILIACION, FECHA_DE_INICIO_DEL_SEGURO,
    FECHA_FIN_DEL_SEGURO, PRIMA_BRUTA, PERIODO_DE_PAGO
FROM `produccion.TRAMAS_diarias_BBVA_2025`
WHERE FECHA_DE_AFILIACION BETWEEN '2025-03-01' AND '2025-03-31' 
    AND TIPO_DE_SEGURO IN ('816', '812', '803' '803_TLMK', '818', '822', '825', '827', '829')
    AND (
    -- Condición especial para tipo_de_seguro = '825'
    (TIPO_DE_SEGURO = '825' AND (
        (TIPO_DE_MOVIMIENTO = '1' AND TIPO_DE_REGISTRO = '07') OR
        (TIPO_DE_MOVIMIENTO = '4' AND TIPO_DE_REGISTRO IN ('00','01'))
    ))
    -- Todos los demás seguros
    OR TIPO_DE_SEGURO != '825'
  );
