CREATE OR REPLACE VIEW `produccion.Vw_ERRORES_desgravamen_prestamos_Detallado` AS
    SELECT CONCAT(SUBSTR(LINEA_TRAMA, 4, 20),'-',SUBSTR(LINEA_TRAMA, 1, 3), '-',
        SUBSTR(LINEA_TRAMA, 377, 8) ,SUBSTR(LINEA_TRAMA, 385, 8)) AS ID_REG, 
        TIPO_SEGURO, FEC__INICIO,FEC__FIN, CODIGO_ERROR, IDEERROR, IDEDET, ORIGEN_ERROR,
        MONEDA, PRIMABRUTACAN, TIPO_MOVIMIENTO, TIPO_MOVIMIENTO_NUM, TIPO_REGISTRO,
        TIPO_ERROR, DESCRIPCION_ERROR, DESCRIPCION_ERROR_SAS, DETALLE, SOLUCION, SOLUCION_2

    FROM `produccion.ERRORES_desgravamen_prestamos`
    WHERE FECHA_CARGA >= '2025-10-18'